### ISSUE TITLE
https://github.com/twitter/bootstrap/issues/6682

### ISSUE THREAD

**Issue by antonellopasella** [BanzaiTokyo/webhostinghub-glyphs#3]
As bootstrap moved from icon- to glyphicon- prefix for icon font (see https://github.com/twitter/bootstrap/issues/6682) I suggest you to move from icon- to whh- or something like this

**Comment by BanzaiTokyo** [comment]
I don't see what the advantage would be? We'd rather keep it "icon-" to make it easier for people who continue to use BS2.0 (and for 3.0 it doesn't make any difference at all).
