### ISSUE TITLE
Add icon for Timetracking software Kimai

### ISSUE THREAD

**Issue by kevinpapst** [BanzaiTokyo/webhostinghub-glyphs#4]
Hi!

I would like to suggest a new Icon for Kimai, which can be found at http://kimai.org/ or here at GitHub https://github.com/kimai/kimai

Thanks for your great work :)
Kevin

**Comment by whhglyphs** [comment]
Sorry for late reply, it will be added in next update. If you have any more requests let us know!

**Comment by whhglyphs** [comment]
Kimai icon was added in the latest update.

**Comment by kevinpapst** [comment]
Thats, very nice!
